import Link from "next/link";
import Head from "next/head";

const Navbar = () => {
    return (
        <>
            <Head>
                <title>Eldoret Soko</title>
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <nav className="navbar navbar-expand-lg navbar-light bg-light">
                <div className="container-fluid">
                    <a className="navbar-brand" href="#">Eldoret Soko</a>
                    <button className="navbar-toggler" type="button" data-bs-toggle="collapse"
                            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span className="navbar-toggler-icon"></span>
                    </button>
                    <div className="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul className="navbar-nav me-auto mb-2 mb-lg-0">
                            <li className="nav-item">
                                <Link href="/" ><a className="nav-link active" aria-current="page">Home</a></Link>
                            </li>
                            <li className="nav-item">
                                <Link href="/admin/houses"  ><a className="nav-link">Houses</a></Link>
                            </li>
                            <li className="nav-item">
                                <Link href="/admin/categories"><a  className="nav-link">Categories</a></Link>
                            </li>
                            <li className="nav-item">
                                <Link href="/admin/locations"><a className="nav-link">Locations</a></Link>
                            </li>
                            <li className="nav-item">
                                <Link href="/admin/locations"><a className="nav-link">Amenities</a></Link>
                            </li>
                        </ul>
                        <form className="d-flex">
                            <input className="form-control me-2" type="search" placeholder="Search" aria-label="Search"/>
                                <button className="btn btn-outline-success" type="submit">Search</button>
                        </form>
                    </div>
                </div>
            </nav>
        </>
    )
}
export default  Navbar